/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/admin/menu': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The admin's whole menu, live and archived.
     * @description # Errors
     *
     *     Returns `401` if nobody is signed in, `403` for a waiter or a chef, and
     *     `503` if the database is unavailable.
     */
    get: operations['admin_menu']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/menu/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Adds a category to the end of the category list.
     * @description It appears on the admin's screen at once, and on waiters' screens as soon as
     *     it holds a live dish: the ordering menu leaves an empty heading out.
     *
     *     # Errors
     *
     *     Returns `400` naming the field that was not accepted, including
     *     `fields.name=already_taken`, `401` if nobody is signed in, and `403` for a
     *     waiter or a chef.
     */
    post: operations['create_category']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/menu/categories/order': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Puts the categories in a new order, the order waiters then see.
     * @description No audit row: a reorder moves nothing of consequence and changes no
     *     version, so it makes no open form stale.
     *
     *     # Errors
     *
     *     Returns `409 menu_changed` if the list is not exactly the live categories,
     *     `401` if nobody is signed in, and `403` for a waiter or a chef.
     */
    put: operations['reorder_categories']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/menu/categories/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Renames a category, provided nobody changed it since the form loaded.
     * @description # Errors
     *
     *     Returns `409 category_changed` if the stored version is newer, `404` if
     *     there is no such live category, `400` naming the field that was not
     *     accepted, `401` if nobody is signed in, and `403` for a waiter or a chef.
     */
    put: operations['rename_category']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/menu/categories/{id}/archive': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Takes a category off the menu. It moves to the Archived section.
     * @description Refused while it still holds a live dish, including one being created in or
     *     moved into it at the same instant: no live dish ever sits in an archived
     *     category.
     *
     *     # Errors
     *
     *     Returns `409 category_not_empty` if it holds a live dish, `404` if there is
     *     no such live category, `401` if nobody is signed in, and `403` for a waiter
     *     or a chef.
     */
    post: operations['archive_category']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/menu/categories/{id}/dish-order': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Puts one category's dishes in a new order.
     * @description A dish cannot be dragged into another category here: moving it is an edit,
     *     made in the edit form, where its version is checked.
     *
     *     # Errors
     *
     *     Returns `409 menu_changed` if the list is not exactly that category's live
     *     dishes, `404` if there is no such live category, `401` if nobody is signed
     *     in, and `403` for a waiter or a chef.
     */
    put: operations['reorder_dishes']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/menu/categories/{id}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Puts an archived category back, at the end of the category list.
     * @description # Errors
     *
     *     Returns `409 name_taken` if a live category now has its name, `404` if
     *     there is no such archived category, `401` if nobody is signed in, and `403`
     *     for a waiter or a chef.
     */
    post: operations['restore_category']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/menu/dishes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Adds a dish to the end of a category.
     * @description # Errors
     *
     *     Returns `400` naming each field that was not accepted, `409
     *     category_archived` if the category has been archived, `404` for a category
     *     this restaurant does not have, `401` if nobody is signed in, and `403` for a
     *     waiter or a chef.
     */
    post: operations['create_dish']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/menu/dishes/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Edits a dish, moving it when its category changes.
     * @description The target category is checked before the version, so an edit that is both
     *     stale and aimed at a removed category reports the category first: that is
     *     what the admin has to change before anything else will save.
     *
     *     # Errors
     *
     *     Returns `400` naming each field that was not accepted, `409
     *     category_archived` if the target category has been archived, `409
     *     dish_changed` if the stored version is newer, `404` if there is no such live
     *     dish or category, `401` if nobody is signed in, and `403` for a waiter or a
     *     chef.
     */
    put: operations['edit_dish']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/menu/dishes/{id}/archive': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Takes a dish off the menu. It moves to the Archived section.
     * @description Every order line, round, and bill that referred to it still resolves and
     *     reads exactly as before: a line copied the name and the price when it was
     *     sent.
     *
     *     # Errors
     *
     *     Returns `404` if there is no such live dish, `401` if nobody is signed in,
     *     and `403` for a waiter or a chef.
     */
    post: operations['archive_dish']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/menu/dishes/{id}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Puts an archived dish back, at the end of a live category.
     * @description It keeps its name, description, price, diet marker, and availability.
     *
     *     # Errors
     *
     *     Returns `409 name_taken` if a live dish now has its name, `409
     *     category_archived` if the chosen category has been archived, `404` if there
     *     is no such archived dish or category, `401` if nobody is signed in, and
     *     `403` for a waiter or a chef.
     */
    post: operations['restore_dish']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Registers a restaurant and signs its owner in as the admin.
     * @description One transaction. Any failure inside it, a duplicate address in particular,
     *     leaves no restaurant, no staff row, and no session: the transaction is
     *     simply dropped, and everything it wrote goes with it.
     *
     *     The five settings the restaurant starts with come from the country's row in
     *     `locales/countries.json` and from nowhere else.
     *
     *     # Errors
     *
     *     Returns a `400` naming each field that was not accepted, including
     *     `fields.email=already_taken` for an address that already has an account, and
     *     a `503` if the database or the password hash is unavailable.
     */
    post: operations['register']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/sign-in': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Signs somebody in.
     * @description The address is looked up across every restaurant, because sign in has a
     *     chicken and egg problem: there is no restaurant to scope to until the
     *     account is found. That lookup is one of exactly two in the system that read
     *     across restaurants, and it is `SECURITY DEFINER` in the database with a
     *     fixed narrow shape.
     *
     *     # Errors
     *
     *     Returns `401` for a wrong password, an address nobody has, and a deactivated
     *     account alike, and a `503` if the database or the password hash is
     *     unavailable.
     */
    post: operations['sign_in']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/sign-out': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Signs out exactly the session that made the request.
     * @description Every other session belonging to the same person keeps working, which is
     *     what makes signing out on the house phone at the end of a shift safe to do.
     *
     *     # Errors
     *
     *     Returns `401` if nobody is signed in, and a `503` if the database is
     *     unavailable.
     */
    post: operations['sign_out']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/dishes/{id}/availability': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * Switches a dish on or off.
     * @description Admins and chefs, and it is the only menu change a chef can make. Every
     *     waiter's ordering screen greys the dish within a second or two, through the
     *     `dish` event this write sends. Never refused as stale; setting the value it
     *     already has succeeds and changes nothing.
     *
     *     # Errors
     *
     *     Returns `404` if there is no such live dish, including one archived a moment
     *     earlier, `401` if nobody is signed in, and `403` for a waiter.
     */
    put: operations['set_availability']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Opens the live stream for the caller's restaurant.
     * @description The stream carries only this restaurant's events, because the server routes
     *     on the restaurant id before it ever writes to a socket. Sending everything
     *     and letting the browser filter would leak ticket volume, timing, and
     *     identifiers between restaurants over the wire, even though the follow up
     *     fetch would be refused.
     *
     *     The client must refetch its active queries every time this opens, including
     *     every reconnect. Postgres queues nothing for a listener that is not
     *     connected, so anything sent during a gap is gone, and without a refetch one
     *     network blip becomes a ticket that never appears in the kitchen.
     */
    get: operations['events']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/floor': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The floor, in the order it is walked.
     * @description # Errors
     *
     *     Returns `401` if nobody is signed in, `403` if the caller is not a waiter,
     *     and `503` if the database is unavailable.
     */
    get: operations['floor']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Reports whether this instance can actually serve.
     * @description Returns 200 only when the pool answers **and** the listen connection is
     *     alive. An instance whose listener has died still answers HTTP perfectly but
     *     delivers no tickets to any kitchen screen, so a check that only proved the
     *     process was up would leave it in service forever.
     */
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/kitchen/tickets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The kitchen queue, oldest first.
     * @description # Errors
     *
     *     Returns `401` if nobody is signed in, `403` if the caller is not a chef, and
     *     `503` if the database is unavailable.
     */
    get: operations['kitchen_tickets']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Who is signed in, and where they work.
     * @description The same bundle sign in returns, so a browser that has reloaded gets back to
     *     exactly the state it had without a second endpoint or a second shape.
     *
     *     # Errors
     *
     *     Returns `401` if nobody is signed in, and a `503` if the database is
     *     unavailable.
     */
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Changes the caller's own display name or personal language.
     * @description # Errors
     *
     *     Returns a `400` naming the field that was not accepted, `401` if nobody is
     *     signed in, and a `503` if the database is unavailable.
     */
    patch: operations['update_me']
    trace?: never
  }
  '/api/me/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Changes the caller's own password, and signs their other devices out.
     * @description The session that made the request keeps working, so somebody changing their
     *     password on the screen in front of them is not immediately signed out of it.
     *     Every other session of theirs is revoked in the same transaction, which is
     *     what makes "I think somebody has my password" a thing they can act on alone.
     *
     *     # Errors
     *
     *     Returns a `400` with `fields.currentPassword=incorrect` for a wrong current
     *     password, `401` if nobody is signed in, and a `503` if the database or the
     *     password hash is unavailable.
     */
    post: operations['change_password']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/menu': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The restaurant's live menu, in printed order.
     * @description # Errors
     *
     *     Returns `401` if nobody is signed in, `403` if the caller is neither a
     *     waiter nor a chef, and `503` if the database is unavailable.
     */
    get: operations['menu']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/order-lines/{id}/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Marks one dish off the pass.
     * @description Touches that dish and nothing else. The ticket's own status follows from all
     *     of its dishes and is recomputed inside the same transaction, which is why
     *     nothing here sets it.
     *
     *     # Errors
     *
     *     Returns `409 line_not_queued` if another chef marked it first, `404` if
     *     there is no such dish, `401` if nobody is signed in, and `403` if the caller
     *     is not a chef.
     */
    post: operations['mark_line_ready']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/restaurant': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Changes the restaurant's settings. Admins only.
     * @description The role requirement is in the signature: `Actor<Admin>` refuses a waiter and
     *     a chef with `403` before this body runs, so there is no line here to forget.
     *
     *     # Errors
     *
     *     Returns a `400` naming each field that was not accepted, `403` for a waiter
     *     or a chef, `401` if nobody is signed in, and a `503` if the database is
     *     unavailable.
     */
    patch: operations['update_restaurant']
    trace?: never
  }
  '/api/rounds/{id}/served': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Marks a whole ticket as having reached the table.
     * @description The one refusal here that is not a repository operation's own. It reads the
     *     ticket first and refuses unless it is `ready` at that moment, because
     *     "somebody has already carried this out" is what the waiter needs to be told,
     *     and a line level message about one dish would not say it.
     *
     *     Inside the loop it marks every dish that is `ready` and skips one that is
     *     already `served` or was cancelled rather than treating either as a conflict.
     *     Two waiters serving the same ticket at the same instant is not a mistake
     *     worth stopping the second one over; only the precheck refuses, and only
     *     because by then the ticket is no longer ready.
     *
     *     # Errors
     *
     *     Returns `409 round_not_ready` if the ticket is not waiting to be carried
     *     out, `404` if there is no such ticket, `401` if nobody is signed in, and
     *     `403` if the caller is not a waiter.
     */
    post: operations['mark_round_served']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/visits': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Seats a party and opens their bill, in one transaction.
     * @description Both or neither. A visit with no bill would be a table that could take an
     *     order nobody could be charged for, and it would be discovered at the end of
     *     the meal.
     *
     *     # Errors
     *
     *     Returns `409 table_occupied` if somebody else opened that table first, `400`
     *     if the table is archived or not this restaurant's, `401` if nobody is signed
     *     in, and `403` if the caller is not a waiter.
     */
    post: operations['open_visit']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/visits/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * One table's whole meal.
     * @description # Errors
     *
     *     Returns `404` if there is no such visit in this restaurant, which is also
     *     the answer for another restaurant's visit so the two cannot be told apart,
     *     `401` if nobody is signed in, and `403` if the caller is not a waiter.
     */
    get: operations['visit']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/visits/{id}/close': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Ends the meal: closes the bill, then closes the visit.
     * @description In that order and in one transaction. `close_visit` refuses while a bill on
     *     the visit is still open, so the order is not a preference; and one
     *     transaction is what stops a bill being numbered and totalled while its table
     *     stays occupied for ever because the second write failed.
     *
     *     # Errors
     *
     *     Returns `409 bill_has_unserved_lines` if a dish has not reached the table,
     *     `409 bill_already_closed` if somebody closed it first, `409
     *     bill_has_no_lines` if nothing was ordered, `404` if there is no such visit or
     *     it has no bill, `401` if nobody is signed in, and `403` if the caller is not
     *     a waiter.
     */
    post: operations['close_visit']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/visits/{id}/rounds': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sends one ticket to the kitchen and puts its dishes on the bill.
     * @description One transaction, so a ticket whose lines are on no bill cannot exist. That
     *     is what keeps the bill's running subtotal true throughout the meal and
     *     leaves the close with no assignment left to do.
     *
     *     # Errors
     *
     *     Returns `400` if the basket is empty or a quantity is not positive, `409
     *     dish_not_orderable` if a dish was switched off or taken off the menu before
     *     the ticket went, which refuses the whole ticket, `409 visit_not_open` if the
     *     party has left, `404` if there is no such visit, `401` if nobody is signed
     *     in, and `403` if the caller is not a waiter.
     */
    post: operations['send_round']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description One live category with its dishes. */
    AdminCategoryDto: {
      /** @description Its live dishes, in printed order. */
      dishes: components['schemas']['DishDto'][]
      /**
       * Format: uuid
       * @description Which category this is.
       */
      id: string
      /** @description What it is called. */
      name: string
      /**
       * Format: int32
       * @description Which edit of the category this is. Send it back with a rename.
       */
      version: number
    }
    /** @description The whole menu as the admin works on it, live and archived. */
    AdminMenuResponse: {
      /** @description What has been taken off the menu and can be put back. */
      archived: components['schemas']['ArchivedMenuDto']
      /**
       * @description Every live category in printed order, each with every live dish in it,
       *     available or not. Unlike the ordering menu, an empty category is kept:
       *     it is exactly the one an admin is about to fill.
       */
      categories: components['schemas']['AdminCategoryDto'][]
      /** @description What this restaurant charges in. */
      currencyCode: string
      /**
       * Format: int32
       * @description How many decimal places that currency uses, which is also how many a
       *     price may carry.
       */
      currencyDecimals: number
    }
    /** @description One archived category. */
    ArchivedCategoryDto: {
      /**
       * Format: date-time
       * @description When it was taken off the menu.
       */
      archivedAt: string
      /**
       * Format: uuid
       * @description Which category this is.
       */
      id: string
      /** @description What it was called. */
      name: string
    }
    /** @description One archived dish, with what the restore dialog needs. */
    ArchivedDishDto: {
      /**
       * Format: date-time
       * @description When it was taken off the menu.
       */
      archivedAt: string
      /**
       * Format: uuid
       * @description The category it was in when it was removed.
       */
      categoryId: string
      /**
       * @description Whether that category is still live. The restore dialog offers it as
       *     the default only when it is.
       */
      categoryLive: boolean
      /**
       * @description What that category is called, carried here because it may be archived
       *     too and so appear nowhere else on the screen.
       */
      categoryName: string
      /** @description Whether it is veg, non veg, or egg. */
      diet: components['schemas']['DietDto']
      /**
       * Format: uuid
       * @description Which dish this is.
       */
      id: string
      /** @description What it is called. */
      name: string
    }
    /** @description Everything in the Archived section. */
    ArchivedMenuDto: {
      /** @description Archived categories, most recently removed first. */
      categories: components['schemas']['ArchivedCategoryDto'][]
      /** @description Archived dishes, most recently removed first. */
      dishes: components['schemas']['ArchivedDishDto'][]
    }
    /**
     * @description A bill, open or closed, with every figure it currently carries.
     *
     *     The currency travels with it rather than being read from the restaurant,
     *     because a closed bill keeps the currency it was charged in even after the
     *     restaurant changes. A screen formatting a bill must use these two and not
     *     the restaurant's current pair.
     */
    BillDto: {
      /**
       * Format: date-time
       * @description When it closed, if it has.
       */
      closedAt?: string | null
      /** @description What it is charged in. */
      currencyCode: string
      /**
       * Format: int32
       * @description How many decimal places that currency uses.
       */
      currencyDecimals: number
      /**
       * Format: uuid
       * @description Which bill this is.
       */
      id: string
      /**
       * Format: int64
       * @description Its number within the restaurant, allocated at close. `null` while open.
       */
      number?: number | null
      /** @description What that rate came to. Zero rather than null when there is none. */
      serviceChargeAmount: string
      /**
       * @description The service charge rate applied, or `null` when the restaurant charges
       *     none.
       */
      serviceChargePercent?: string | null
      /** @description Whether it is still collecting dishes. */
      status: string
      /** @description The sum of its dishes that were not cancelled. */
      subtotal: string
      /** @description The sum of the tax lines. */
      taxTotal: string
      /** @description The tax breakdown, empty until it closes. */
      taxes: components['schemas']['BillTaxDto'][]
      /** @description Subtotal plus service charge plus taxes, with no residue. */
      total: string
    }
    /** @description One tax line copied onto a bill when it closed. */
    BillTaxDto: {
      /** @description What that came to, already rounded to the bill's currency. */
      amount: string
      /** @description What the tax was called at the time. */
      name: string
      /** @description What rate was charged, as an exact decimal string. */
      ratePercent: string
    }
    /** @description One category, as a write on it answers. */
    CategoryDto: {
      /**
       * Format: date-time
       * @description When it was taken off the menu, or `null` while it is on it.
       */
      archivedAt?: string | null
      /**
       * Format: uuid
       * @description Which category this is.
       */
      id: string
      /** @description What it is called. */
      name: string
      /**
       * Format: int32
       * @description Which edit of the category this is.
       */
      version: number
    }
    /** @description What changing your own password asks for. */
    ChangePasswordRequest: {
      /** @description The password they are signing in with now. */
      currentPassword: string
      /** @description What they want it to be. */
      newPassword: string
    }
    /**
     * @description Whether one dependency is answering.
     * @enum {string}
     */
    Component: 'up' | 'down'
    /** @description What adding a category asks for. */
    CreateCategoryRequest: {
      /**
       * @description What it is called. At most 60 characters, unique among live categories
       *     ignoring letter case.
       */
      name: string
    }
    /**
     * @description What adding a dish asks for.
     *
     *     No availability: a new dish is available, and only the switch changes that.
     *     No position: it goes to the end of its category.
     */
    CreateDishRequest: {
      /**
       * Format: uuid
       * @description Which live category it goes in.
       */
      categoryId: string
      /** @description What it is, for the waiter to read out. At most 300 characters. */
      description?: string | null
      /** @description Whether it is veg, non veg, or egg. Required. */
      diet: components['schemas']['DietDto']
      /**
       * @description What it is called. At most 80 characters, unique among live dishes
       *     ignoring letter case.
       */
      name: string
      /**
       * @description What it costs, as a decimal string such as `"320.50"`. Never a JSON
       *     number. Zero or more, below ten billion, and no more decimal places than
       *     the restaurant's currency uses.
       */
      price: string
    }
    /**
     * @description Whether a dish is veg, non veg, or egg, on the wire.
     *
     *     The same three words the `dish_diet` enum stores, kept that way by the test
     *     at the foot of this file.
     * @enum {string}
     */
    DietDto: 'veg' | 'non_veg' | 'egg'
    /**
     * @description One dish, with everything an admin's edit form needs.
     *
     *     What every menu write answers with, and what the admin menu lists. The
     *     `version` is the one the form sends back, which is how an edit made from a
     *     stale form is told apart from a current one.
     */
    DishDto: {
      /**
       * Format: date-time
       * @description When it was taken off the menu, or `null` while it is on it.
       */
      archivedAt?: string | null
      /** @description Whether the kitchen can make it right now. */
      available: boolean
      /**
       * Format: uuid
       * @description Which category it sits under.
       */
      categoryId: string
      /** @description What it is, for the waiter to read out. `null` when there is none. */
      description?: string | null
      /** @description Whether it is veg, non veg, or egg. */
      diet: components['schemas']['DietDto']
      /**
       * Format: uuid
       * @description Which dish this is.
       */
      id: string
      /** @description What it is called. */
      name: string
      /** @description What it costs, as an exact decimal string. Never a JSON number. */
      price: string
      /**
       * Format: int32
       * @description Which edit of the dish this is. Send it back with an edit.
       */
      version: number
    }
    /**
     * @description What editing a dish asks for: everything the dish should be, and which
     *     version of it the form loaded.
     *
     *     No availability. Only the switch writes that, so an edit form opened before
     *     the kitchen switched a dish off cannot switch it back on; the switch bumps
     *     the version, and the form's save is refused as stale.
     */
    EditDishRequest: {
      /**
       * Format: uuid
       * @description Which live category it should sit under. A different one moves it to
       *     the end of that category.
       */
      categoryId: string
      /** @description What it is, or `null` for no description. */
      description?: string | null
      /** @description Whether it is veg, non veg, or egg. */
      diet: components['schemas']['DietDto']
      /** @description What it should be called. */
      name: string
      /**
       * @description What it should cost, as a decimal string. Lines already sent keep the
       *     price they copied.
       */
      price: string
      /**
       * Format: int32
       * @description The version the edit form loaded.
       */
      version: number
    }
    /** @description The body every failed request returns. */
    ErrorBody: {
      /**
       * @description A stable machine readable code, safe to branch on in the client.
       *
       *     A refused conflict names which conflict it was, such as
       *     `table_occupied` or `bill_has_unserved_lines`, rather than the blanket
       *     word `conflict`. The closed list is
       *     [`ConflictKind`](crate::domain::error::ConflictKind).
       * @example not_found
       */
      error: string
      /**
       * @description What is wrong with each named field, when the problem is a form rather
       *     than the request as a whole.
       *
       *     Absent from every response that has no field level problem, which is
       *     most of them, so nothing that was already reading this body changes.
       *     Each value is one of a closed set of codes: `already_taken`,
       *     `too_short`, `too_long`, `invalid_format`, `unknown_country`,
       *     `not_in_catalogue`, `incorrect`, `required`, `not_a_number`,
       *     `negative`, `too_large`, `too_many_decimals`.
       * @example {
       *       "email": "already_taken"
       *     }
       */
      fields?: {
        [key: string]: string
      } | null
      /**
       * @description A human readable sentence. Never contains internal detail.
       *
       *     English, and for a log. The web app renders a translation of
       *     [`Self::error`] instead, because the API is a data API and knows nothing
       *     about what language anybody reads.
       * @example The requested resource does not exist.
       */
      message: string
    }
    /** @description Every table in the restaurant, grouped by section. */
    FloorResponse: {
      /** @description The sections, in displayed order, each with its tables. */
      sections: components['schemas']['FloorSectionDto'][]
    }
    /** @description One group of tables. */
    FloorSectionDto: {
      /**
       * Format: uuid
       * @description Which section this is, or `null` for the group holding tables that
       *     belong to no live section.
       */
      id?: string | null
      /**
       * @description What it is called, or `null` for that same group. A screen shows those
       *     tables under a heading of its own choosing, in its own language.
       */
      name?: string | null
      /** @description Its tables, in displayed order. */
      tables: components['schemas']['FloorTableDto'][]
    }
    /** @description One table, and whoever is sitting at it. */
    FloorTableDto: {
      /**
       * Format: uuid
       * @description Which table this is.
       */
      id: string
      /** @description What the staff call it, such as `12` or `Bar 3`. */
      label: string
      occupancy?: null | components['schemas']['OccupancyDto']
      /**
       * Format: int32
       * @description How many it seats, when the restaurant recorded it.
       */
      seats?: number | null
    }
    /**
     * @description What the health endpoint returns.
     *
     *     A presentation DTO rather than the application's `HealthReport`, so that the
     *     wire format can change without touching a use case, and so that no inner
     *     layer has to know the `utoipa` schema traits exist.
     */
    HealthResponse: {
      /** @description Whether the connection pool answers. */
      database: components['schemas']['Component']
      /** @description Whether this instance's Postgres listen connection is up. */
      listener: components['schemas']['Component']
      /** @description True only when every dependency is up. */
      serving: boolean
    }
    /**
     * @description Everything the browser needs to know who it is talking for.
     *
     *     Returned identically by register, sign in, `GET /api/me`, `PATCH /api/me`,
     *     and `PATCH /api/restaurant`, so the browser has one type and one cache
     *     entry. Five endpoints returning five nearly identical shapes is how a client
     *     ends up with five slightly different ideas of who is signed in.
     */
    IdentityBundle: {
      /** @description Where they work. */
      restaurant: components['schemas']['RestaurantDto']
      /** @description Who is signed in. */
      staff: components['schemas']['StaffDto']
    }
    /**
     * @description One dish on a kitchen ticket.
     *
     *     Deliberately narrower than [`OrderLineDto`]. A kitchen screen has no
     *     business showing a price, and a chef tapping a dish done should not be one
     *     misread column away from the bill.
     */
    KitchenLineDto: {
      /** @description What to cook. */
      dishName: string
      /**
       * Format: uuid
       * @description Which line this is. What the mark ready call names.
       */
      id: string
      /** @description What the guest asked for, such as no onions. Reaches the pass unchanged. */
      note?: string | null
      /**
       * Format: int32
       * @description How many.
       */
      quantity: number
      /** @description Where this one dish has got to. */
      status: components['schemas']['LineStatusDto']
    }
    /** @description Everything the kitchen still has work on. */
    KitchenResponse: {
      /**
       * Format: date-time
       * @description What the server's clock reads, at the moment this answer was built.
       *
       *     The screen subtracts this from its own clock and corrects every age it
       *     draws by the difference. A kitchen tablet whose clock is twenty minutes
       *     fast would otherwise show every ticket as twenty minutes late, and the
       *     one number a chef acts on would be the one number nobody could trust.
       */
      serverTime: string
      /** @description The tickets, oldest first. */
      tickets: components['schemas']['KitchenTicketDto'][]
    }
    /** @description One ticket on the kitchen screen. */
    KitchenTicketDto: {
      /**
       * Format: uuid
       * @description Which ticket this is.
       */
      id: string
      /** @description Every dish on it, oldest first. */
      lines: components['schemas']['KitchenLineDto'][]
      /**
       * Format: date-time
       * @description When it reached the kitchen. The waiting time is measured from here.
       */
      sentAt: string
      /**
       * Format: int32
       * @description Its number within the visit, so a chef can say "table 4, second round".
       */
      sequenceNo: number
      /** @description Where the whole ticket has got to. */
      status: components['schemas']['RoundStatusDto']
      /** @description Where the food is going. */
      tableLabel: string
    }
    /**
     * @description Where one dish has got to, on the wire.
     * @enum {string}
     */
    LineStatusDto: 'queued' | 'ready' | 'served' | 'voided'
    /** @description What marking one dish changed. */
    MarkedLineResponse: {
      /** @description The dish, after the write. */
      line: components['schemas']['OrderLineDto']
      /**
       * @description What the whole ticket became, recomputed from all of its dishes. The
       *     kitchen screen uses this to drop a ticket that has just gone ready.
       */
      roundStatus: components['schemas']['RoundStatusDto']
    }
    /** @description One group of dishes. */
    MenuCategoryDto: {
      /** @description Its dishes, in printed order. */
      dishes: components['schemas']['MenuDishDto'][]
      /**
       * Format: uuid
       * @description Which category this is.
       */
      id: string
      /** @description What it is called. */
      name: string
    }
    /** @description One item on the menu. */
    MenuDishDto: {
      /**
       * @description Whether the kitchen can make it right now. `false` greys it on the
       *     ordering screen and stops it being added to a basket.
       */
      available: boolean
      /** @description What it is, for the waiter to read out. */
      description?: string | null
      /** @description Whether it is veg, non veg, or egg, drawn as the square mark. */
      diet: components['schemas']['DietDto']
      /**
       * Format: uuid
       * @description Which dish this is.
       */
      id: string
      /** @description What it is called today. */
      name: string
      /** @description What it costs, as an exact decimal string. Never a JSON number. */
      price: string
    }
    /** @description The whole menu, grouped the way it is printed. */
    MenuResponse: {
      /**
       * @description The live categories, in printed order. A category with no live dish is
       *     left out, because an empty heading on a phone is a row of wasted space.
       */
      categories: components['schemas']['MenuCategoryDto'][]
      /**
       * @description What this restaurant charges in. Carried here rather than left to the
       *     screen to look up, so a price and the currency it is in arrive together.
       */
      currencyCode: string
      /**
       * Format: int32
       * @description How many decimal places that currency uses.
       */
      currencyDecimals: number
    }
    /** @description What a waiter needs to know about an occupied table without opening it. */
    OccupancyDto: {
      /** @description Whether a ticket on this visit is waiting to be carried out. */
      foodReady: boolean
      /**
       * Format: int32
       * @description How many of them, when the waiter recorded it.
       */
      guestCount?: number | null
      /**
       * Format: date-time
       * @description When they sat down.
       */
      openedAt: string
      /** @description What to call the waiter who seated them. */
      openedBy: string
      /**
       * Format: uuid
       * @description The one open visit on this table.
       */
      visitId: string
    }
    /** @description What seating a party asks for. */
    OpenVisitRequest: {
      /**
       * Format: int32
       * @description How many of them, if the waiter counted.
       */
      guestCount?: number | null
      /**
       * Format: uuid
       * @description Which table they are sitting at.
       */
      tableId: string
    }
    /** @description The visit and the bill that were created together. */
    OpenVisitResponse: {
      /**
       * Format: uuid
       * @description The bill their dishes will go on.
       */
      billId: string
      /**
       * Format: uuid
       * @description The party's stay at the table.
       */
      visitId: string
    }
    /**
     * @description One dish on one ticket, as every screen reads it.
     *
     *     The name and the price are the ones copied onto the line when the round was
     *     sent, not today's menu. That is what lets a bill from last Tuesday stay
     *     true after a reprice.
     */
    OrderLineDto: {
      /**
       * Format: uuid
       * @description Which menu item it came from.
       */
      dishId: string
      /** @description What the dish was called when it was ordered. */
      dishName: string
      /**
       * Format: uuid
       * @description Which line this is.
       */
      id: string
      /** @description Quantity times unit price, as an exact decimal string. */
      lineTotal: string
      /** @description What the guest asked for, such as no onions. */
      note?: string | null
      /**
       * Format: int32
       * @description How many.
       */
      quantity: number
      /** @description Where this one dish has got to. */
      status: components['schemas']['LineStatusDto']
      /** @description What one of them cost, as an exact decimal string. */
      unitPrice: string
    }
    /** @description One ticket with its dishes. */
    OrderRoundDto: {
      /**
       * Format: uuid
       * @description Which ticket this is.
       */
      id: string
      /** @description Every dish on it, oldest first. */
      lines: components['schemas']['OrderLineDto'][]
      /**
       * Format: date-time
       * @description When the last dish came off the pass.
       */
      readyAt?: string | null
      /**
       * Format: date-time
       * @description When it reached the kitchen.
       */
      sentAt: string
      /**
       * Format: int32
       * @description Its number within the visit, starting at one.
       */
      sequenceNo: number
      /**
       * Format: date-time
       * @description When the last dish reached the table.
       */
      servedAt?: string | null
      /** @description Where the whole ticket has got to, recomputed from its dishes. */
      status: components['schemas']['RoundStatusDto']
      /**
       * Format: uuid
       * @description Which visit it belongs to.
       */
      visitId: string
    }
    /**
     * @description What registration asks for.
     *
     *     Five fields, and that is the product decision showing through: trying this
     *     costs a minute, not an afternoon of settings. Everything else about the
     *     restaurant is derived from the country or changed later.
     */
    RegisterRequest: {
      /**
       * @description Where the restaurant is, as an ISO 3166-1 alpha-2 code. Accepted in any
       *     case.
       */
      countryCode: string
      /** @description What to call the owner on screen. */
      displayName: string
      /** @description The address they will sign in with. */
      email: string
      /** @description Their password. At least 10 characters. */
      password: string
      /** @description What the restaurant is called. */
      restaurantName: string
    }
    /** @description What renaming a category asks for. */
    RenameCategoryRequest: {
      /** @description What it should be called. */
      name: string
      /**
       * Format: int32
       * @description The version the rename form loaded. An older one is refused as stale.
       */
      version: number
    }
    /**
     * @description What a reorder asks for: the complete list, in its new order.
     *
     *     The whole list rather than a move, so the server never has to guess what
     *     "after that one" meant when the list changed underneath the drag. A list
     *     that is not exactly the live set is refused with `409 menu_changed`.
     */
    ReorderRequest: {
      /** @description Every live id in the list, each exactly once, in the new order. */
      ids: string[]
    }
    /**
     * @description The restaurant the signed in person works at, as every screen reads it.
     *
     *     Carries the five settings spec 0005's formatting layer needs and nothing
     *     about money beyond the currency: figures on a bill come from the bill.
     */
    RestaurantDto: {
      /** @description Where it is, for printing on a bill. `null` when nobody has set one. */
      address?: string | null
      /** @description Where it is, as an ISO 3166-1 alpha-2 code. */
      countryCode: string
      /** @description What it charges in. */
      currencyCode: string
      /**
       * Format: int32
       * @description How many decimal places that currency uses.
       */
      currencyDecimals: number
      /**
       * @description What the kitchen screen reads, and the fallback for anybody with no
       *     personal setting.
       */
      defaultLanguage: string
      /**
       * @description How money, numbers, dates, and times are written here. Deliberately not
       *     derived from the language.
       */
      formattingLocale: string
      /**
       * Format: uuid
       * @description Which restaurant this is.
       */
      id: string
      /** @description What it is called. */
      name: string
      /**
       * @description Its own IANA timezone. Every timestamp on a screen is converted with it,
       *     never with the device's.
       */
      timezone: string
    }
    /** @description What restoring a dish asks for. */
    RestoreDishRequest: {
      /**
       * Format: uuid
       * @description Which live category to put it in. The dialog offers the dish's old one
       *     when that is still live.
       */
      categoryId: string
    }
    /**
     * @description What a member of staff is allowed to be, on the wire.
     *
     *     A separate enum from [`StaffRole`] because that one lives in the domain and
     *     may not learn that `utoipa` exists. The strings are identical, and the two
     *     tests below are what keep them that way.
     * @enum {string}
     */
    RoleDto: 'admin' | 'waiter' | 'chef'
    /**
     * @description Where a whole ticket has got to, on the wire.
     * @enum {string}
     */
    RoundStatusDto: 'queued' | 'ready' | 'served' | 'voided'
    /** @description One dish in the basket. */
    SendRoundLine: {
      /**
       * Format: uuid
       * @description Which menu item.
       */
      dishId: string
      /** @description What the guest asked for, such as no onions. */
      note?: string | null
      /**
       * Format: int32
       * @description How many.
       */
      quantity: number
    }
    /**
     * @description What sending a ticket asks for.
     *
     *     No price anywhere in it, and that is the point. The price and the name are
     *     read from the dish inside `send_round` and copied onto the line, so a client
     *     cannot name its own price however it is built.
     */
    SendRoundRequest: {
      /** @description The basket, one entry per dish. At least one. */
      lines: components['schemas']['SendRoundLine'][]
    }
    /** @description What the availability switch asks for. */
    SetAvailabilityRequest: {
      /**
       * @description What the dish should be: `true` for orderable, `false` for off. An
       *     absolute value, never a toggle, so two quick taps cannot cancel out.
       */
      available: boolean
    }
    /** @description What signing in asks for. */
    SignInRequest: {
      /** @description The address the account was registered with. Matched case insensitively. */
      email: string
      /** @description The password. */
      password: string
    }
    /** @description Who the signed in person is. */
    StaffDto: {
      /** @description What to call them on screen. */
      displayName: string
      /**
       * @description The address they sign in with, exactly as they typed it when they
       *     registered. Handed back unflattened so the account screen shows them
       *     their own capitalisation.
       */
      email: string
      /**
       * Format: uuid
       * @description Which staff member this is.
       *
       *     A bare uuid rather than the domain's `StaffId`, because a newtype in
       *     `domain/` may not learn that `utoipa` exists. The wire has always been
       *     where identifiers lose their types.
       */
      id: string
      /**
       * @description Their own interface language, or `null` for "whatever the restaurant
       *     uses", which is what a new account has.
       */
      language?: string | null
      /** @description What they are allowed to be. */
      role: components['schemas']['RoleDto']
    }
    /**
     * @description What one message on the stream looks like.
     *
     *     A kind and an id, never row content. The client uses it to refetch or to
     *     patch its query cache, which keeps row level security the single authority
     *     on who may see what: a client that should not see a row simply gets nothing
     *     back when it asks for it.
     */
    StreamEvent: {
      /**
       * @description What kind of thing changed, for example `probe`.
       * @example probe
       */
      entity: string
      /**
       * Format: uuid
       * @description Which one changed.
       */
      entity_id: string
    }
    /**
     * @description What somebody may change about their own account.
     *
     *     Both fields are optional and absent means "leave it alone". `language` is
     *     deliberately `Option<Option<String>>`: absent leaves it, and an explicit
     *     `null` clears it, which is a real choice somebody makes rather than an
     *     absence. Collapsing the two would make "follow the restaurant" unsayable.
     */
    UpdateMeRequest: {
      /** @description What to call them on screen. */
      displayName?: string | null
      /**
       * @description Their own interface language, or `null` to follow the restaurant.
       *
       *     Clippy is overruled here, and the reason is the whole point of the
       *     field. The three states are genuinely different and all three have to be
       *     sayable: absent means "do not touch my language", `null` means "follow
       *     the restaurant", and a code means that code. A custom enum would say the
       *     same thing with a hand written `Deserialize` and a hand written
       *     `ToSchema`, and the wire shape would be identical.
       */
      language?: string | null
    }
    /**
     * @description What an admin may change about the restaurant.
     *
     *     No money setting appears here at all. The currency and its decimals were
     *     fixed by the country at registration and changing them under bills that have
     *     already closed would rewrite history.
     */
    UpdateRestaurantRequest: {
      /** @description Where it is, for printing on a bill. An empty string clears it. */
      address?: string | null
      /** @description What the kitchen screen reads. */
      defaultLanguage?: string | null
      /** @description How it writes money, numbers, and dates. */
      formattingLocale?: string | null
      /** @description What the restaurant is called. */
      name?: string | null
      /** @description Its IANA timezone. */
      timezone?: string | null
    }
    /** @description One table's whole meal, as the waiter's screen reads it. */
    VisitResponse: {
      bill?: null | components['schemas']['BillDto']
      /**
       * Format: int32
       * @description How many of them, when the waiter recorded it.
       */
      guestCount?: number | null
      /**
       * Format: uuid
       * @description Which visit this is.
       */
      id: string
      /**
       * Format: date-time
       * @description When they sat down.
       */
      openedAt: string
      /** @description What to call the waiter who seated them. */
      openedBy: string
      /** @description Every ticket on the visit, oldest first, with its dishes. */
      rounds: components['schemas']['OrderRoundDto'][]
      /**
       * Format: date-time
       * @description What the server's clock reads, at the moment this answer was built. The
       *     screen corrects every age it draws by the difference from its own clock.
       */
      serverTime: string
      /** @description Whether they are still there: `open` or `closed`. */
      status: string
      /**
       * Format: uuid
       * @description Which table they are at.
       */
      tableId: string
      /** @description What the staff call that table. */
      tableLabel: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  admin_menu: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The whole menu, live and archived. Admins only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminMenuResponse']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not an admin. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  create_category: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCategoryRequest']
      }
    }
    responses: {
      /** @description The category, at the end of the list. Admins only. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoryDto']
        }
      }
      /** @description A field was not accepted. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not an admin. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  reorder_categories: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderRequest']
      }
    }
    responses: {
      /** @description The live categories in their new order. Admins only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoryDto'][]
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not an admin. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description `menu_changed`: the list is not the live set any more. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  rename_category: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The category to rename. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RenameCategoryRequest']
      }
    }
    responses: {
      /** @description The renamed category. Admins only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoryDto']
        }
      }
      /** @description A field was not accepted. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not an admin. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such live category. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description `category_changed`: somebody changed it after the form loaded. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  archive_category: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The category to remove. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The archived category. Admins only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoryDto']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not an admin. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such live category. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description `category_not_empty`: it still holds a live dish. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  reorder_dishes: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The category whose dishes are being ordered. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderRequest']
      }
    }
    responses: {
      /** @description The category's live dishes in their new order. Admins only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DishDto'][]
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not an admin. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such live category. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description `menu_changed`: the list is not the live set any more. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  restore_category: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The archived category to put back. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The category, live again. Admins only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CategoryDto']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not an admin. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such archived category. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description `name_taken`: a live category has that name now. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  create_dish: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDishRequest']
      }
    }
    responses: {
      /** @description The dish, available, at the end of its category. Admins only. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DishDto']
        }
      }
      /** @description A field was not accepted. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not an admin. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such category. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description `category_archived`: that category is no longer on the menu. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  edit_dish: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The dish to edit. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EditDishRequest']
      }
    }
    responses: {
      /** @description The dish after the edit. Admins only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DishDto']
        }
      }
      /** @description A field was not accepted. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not an admin. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such live dish or category. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description `category_archived` or `dish_changed`. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  archive_dish: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The dish to remove. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The archived dish. Admins only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DishDto']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not an admin. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such live dish. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  restore_dish: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The archived dish to put back. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RestoreDishRequest']
      }
    }
    responses: {
      /** @description The dish, live again. Admins only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DishDto']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not an admin. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such archived dish or category. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description `name_taken` or `category_archived`. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  register: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest']
      }
    }
    responses: {
      /** @description The restaurant and its admin now exist, and the response sets the session cookie. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IdentityBundle']
        }
      }
      /** @description A field was not accepted. `fields.email=already_taken` when that address already has an account. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  sign_in: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SignInRequest']
      }
    }
    responses: {
      /** @description Signed in, and the response sets the session cookie. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IdentityBundle']
        }
      }
      /** @description Identical for a wrong password and for an address nobody has. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  sign_out: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Signed out, and the response clears the cookie. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Nobody was signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  set_availability: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The dish to switch. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SetAvailabilityRequest']
      }
    }
    responses: {
      /** @description The dish after the switch. Admins and chefs. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DishDto']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description A waiter asked. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such live dish. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  events: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A server sent event stream. Each message is named `entity_changed` and its data is a StreamEvent. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/event-stream': components['schemas']['StreamEvent']
        }
      }
      /** @description Nobody is signed in, so there is no restaurant to stream. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  floor: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Every live table and its occupancy. Waiters only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FloorResponse']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not a waiter. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Every dependency is up and this instance can serve. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description A dependency is down. Take this instance out of service. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  kitchen_tickets: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Every queued or ready ticket, oldest first. Chefs only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['KitchenResponse']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not a chef. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The signed in identity. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IdentityBundle']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  update_me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMeRequest']
      }
    }
    responses: {
      /** @description The updated identity. Any signed in role, own row only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IdentityBundle']
        }
      }
      /** @description A field was not accepted. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  change_password: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest']
      }
    }
    responses: {
      /** @description Changed. Any signed in role, own row only. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The current password was wrong, or the new one broke a rule. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  menu: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The live menu. Waiters and chefs. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MenuResponse']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Neither a waiter nor a chef. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  mark_line_ready: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The dish to mark off the pass. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The dish and its ticket's new status. Chefs only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MarkedLineResponse']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not a chef. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such dish. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Somebody marked that dish first. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  update_restaurant: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRestaurantRequest']
      }
    }
    responses: {
      /** @description The updated identity. Admins only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IdentityBundle']
        }
      }
      /** @description A field was not accepted. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description A waiter or a chef asked. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  mark_round_served: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The ticket that reached the table. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The ticket after the write. Waiters only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OrderRoundDto']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not a waiter. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such ticket. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description That ticket is not waiting to be carried out. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  open_visit: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OpenVisitRequest']
      }
    }
    responses: {
      /** @description The visit and its bill. Waiters only. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OpenVisitResponse']
        }
      }
      /** @description No such live table. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not a waiter. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description That table already has a party at it. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  visit: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The visit to read. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The visit, its rounds, and its bill. Waiters only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VisitResponse']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not a waiter. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such visit. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  close_visit: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The visit to close. */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The closed bill, with its number and every figure. Waiters only. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BillDto']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not a waiter. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such visit, or it has no bill. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description A dish is still out, or the bill has already closed. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  send_round: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The visit to send the ticket for. */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SendRoundRequest']
      }
    }
    responses: {
      /** @description The ticket that was sent. Waiters only. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OrderRoundDto']
        }
      }
      /** @description An empty basket, or a quantity below one. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Nobody is signed in. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description Not a waiter. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description No such visit. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
      /** @description `visit_not_open`: that party has already left. `dish_not_orderable`: a dish went off before the ticket went, and nothing was sent. */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
}
