/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Opens the live stream for the caller's restaurant.
     * @description The stream carries only this restaurant's events, because the server routes
     *     on the restaurant id before it ever writes to a socket. Sending everything
     *     and letting the browser filter would leak ticket volume, timing, and
     *     identifiers between restaurants over the wire, even though the follow up
     *     fetch would be refused.
     *
     *     The client must refetch its active queries every time this opens, including
     *     every reconnect. Postgres queues nothing for a listener that is not
     *     connected, so anything sent during a gap is gone, and without a refetch one
     *     network blip becomes a ticket that never appears in the kitchen.
     */
    get: operations['events']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Reports whether this instance can actually serve.
     * @description Returns 200 only when the pool answers **and** the listen connection is
     *     alive. An instance whose listener has died still answers HTTP perfectly but
     *     delivers no tickets to any kitchen screen, so a check that only proved the
     *     process was up would leave it in service forever.
     */
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * @description Whether one dependency is answering.
     * @enum {string}
     */
    Component: 'up' | 'down'
    /** @description The body every failed request returns. */
    ErrorBody: {
      /**
       * @description A stable machine readable code, safe to branch on in the client.
       * @example not_found
       */
      error: string
      /**
       * @description A human readable sentence. Never contains internal detail.
       * @example The requested resource does not exist.
       */
      message: string
    }
    /**
     * @description What the health endpoint returns.
     *
     *     A presentation DTO rather than the application's `HealthReport`, so that the
     *     wire format can change without touching a use case, and so that no inner
     *     layer has to know the `utoipa` schema traits exist.
     */
    HealthResponse: {
      /** @description Whether the connection pool answers. */
      database: components['schemas']['Component']
      /** @description Whether this instance's Postgres listen connection is up. */
      listener: components['schemas']['Component']
      /** @description True only when every dependency is up. */
      serving: boolean
    }
    /**
     * @description What one message on the stream looks like.
     *
     *     A kind and an id, never row content. The client uses it to refetch or to
     *     patch its query cache, which keeps row level security the single authority
     *     on who may see what: a client that should not see a row simply gets nothing
     *     back when it asks for it.
     */
    StreamEvent: {
      /**
       * @description What kind of thing changed, for example `probe`.
       * @example probe
       */
      entity: string
      /**
       * Format: uuid
       * @description Which one changed.
       */
      entity_id: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  events: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A server sent event stream. Each message is named `entity_changed` and its data is a StreamEvent. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/event-stream': components['schemas']['StreamEvent']
        }
      }
      /** @description No session, so no restaurant to stream. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ErrorBody']
        }
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Every dependency is up and this instance can serve. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description A dependency is down. Take this instance out of service. */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
}
